# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tematic_feed.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tematic_feed.proto\"T\n\x0b\x46\x65\x65\x64Request\x12\x0f\n\x07user_id\x18\x01 \x01(\x05\x12\x1f\n\x08\x63\x61tegory\x18\x02 \x01(\x0e\x32\r.PostCategory\x12\x13\n\x0bmax_results\x18\x03 \x01(\x05\"%\n\x08PostFeed\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"2\n\x0c\x46\x65\x65\x64Response\x12\"\n\x0frecommendations\x18\x01 \x03(\x0b\x32\t.PostFeed*A\n\x0cPostCategory\x12\x0f\n\x0b\x44\x45VELOPMENT\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\x0b\n\x07TESTING\x10\x02\x32;\n\x0fRecommendations\x12(\n\tRecommend\x12\x0c.FeedRequest\x1a\r.FeedResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tematic_feed_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSTCATEGORY._serialized_start=199
  _POSTCATEGORY._serialized_end=264
  _FEEDREQUEST._serialized_start=22
  _FEEDREQUEST._serialized_end=106
  _POSTFEED._serialized_start=108
  _POSTFEED._serialized_end=145
  _FEEDRESPONSE._serialized_start=147
  _FEEDRESPONSE._serialized_end=197
  _RECOMMENDATIONS._serialized_start=266
  _RECOMMENDATIONS._serialized_end=325
# @@protoc_insertion_point(module_scope)
